# www.bastiankroggel.com
title: The Day He Is Out Of Office
cr_date: 2018
baseurl: "" # the subpath of your site, e.g. /blog
url: "localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com

excerpt_separator: <!-- more -->
# Build settings
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - airtable

sass:
  style: compressed

encoding: utf-8

#default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "OOOStaff"
      permalink: /blog/:year/:title/

compress_html:
  clippings: all
  comments: all
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
