product: label
price: '10.00'
currency: USD
images:
  - /assets/images/media_library/img_4249.jpg
  - /assets/images/media_library/img_4259.jpg
  - /assets/images/media_library/img_4283.jpg
  - /assets/images/media_library/img_4361.jpg
  - /assets/images/media_library/img_4369.jpg
  - /assets/images/media_library/img_4402.jpg
active: false
button_text: Available Soon
description: >-
  No matter what brand and sort of beer you'll put our label on it will be the
  best beer of your life because of what it stands for. Therefore, we want to
  provide you with the best label you ever had on a bottle of beer: 


  * High quality print on extra thick cotton paper

  * Every label is numbered. This makes not only every label unique but more
  importantly, let's you know how big our movement already is.

  * Water resistant - you can drop the bottle in a bucket full of ice if you
  think it is time to start the party soon. 


  The label will come in a blue envelope in which you will find some
  merchandise.
