backend:
  name: github
  repo: thedayheisooo/covfefe

media_folder: "assets/images/media_library"
display_url: https://thedayheisooo.com
logo_url: 'https://thedayheisooo.netlify.com/assets/images/dev/ooo_pri_col_rgb.svg'

collections:
  - name: 'sites'
    label: "Sites"
    delete: false
    editor:
        preview: false
    files:
      - name: 'index'
        label: "Main"
        file: "index.md"
        extension: "md"
        fields:
          - label: 'Layout'
            name: 'layout'
            widget: 'hidden'
            default: 'home'
            required: true
          - label: 'Claim'
            name: title-claim
            widget: 'string'
          - label: 'Intro'
            name: 'intro'
            widget: 'object'
            fields:
              - label: 'Title'
                name: 'title'
                widget: 'string'
              - label: 'Content'
                name: 'text'
                widget: 'markdown'
              - label: 'Reasons'
                name: 'reasons'
                widget: 'list'
                field:
                  label: 'Reason'
                  name: 'reason'
                  widget: 'string'
              - label: 'Numbers'
                name: 'numbers'
                widget: 'list'
                fields:
                  - { label: Number, name: number, widget: string }
                  - { label: Title, name: title, widget: string }
                  - { label: Text, name: text, widget: markdown }
          - label: '3 Ways'
            name: '3way'
            widget: 'object'
            fields:
              - label: 'Title'
                name: 'title'
                widget: 'string'
              - label: 'Intro'
                name: 'intro'
                widget: 'markdown'
              - label: 'Ways'
                name: 'ways'
                widget: 'list'
                fields:
                  - { label: Title, name: title, widget: string }
                  - { label: Number, name: number, widget: string }
                  - { label: Content, name: content, widget: markdown }
                  - label: 'Button'
                    name: 'button'
                    widget: 'object'
                    fields:
                      - { label: Text, name: text, widget: string }
                      - { label: URL, name: url, widget: string }
                  - { label: Pending?, name: pending, widget: boolean }
          - label: 'FAQ'
            name: 'faq'
            widget: 'object'
            fields:
              - { label: Title of More Section, name: more_title, widget: string }
              - { label: Content of More Section, name: more_content, widget: markdown }
          - label: 'Quote'
            name: 'quote'
            widget: 'object'
            fields:
              - { label: 'Quote Content', name: content, widget: string }
              - { label: Author, name: author, widget: string }
              - { label: Date, name: date, widget: date, format: 'MMM. DD, YYYY' }
              - { label: Description, name: desc, widget: text }
          - label: 'Shop Intro'
            name: 'shop_intro'
            widget: 'markdown'
          - label: 'How To'
            name: 'how_to'
            widget: 'object'
            fields:
              - label: 'Steps'
                name: 'steps'
                widget: 'list'
                fields:
                  - { label: 'Step Description', name: desc, widget: markdown }
                  - { label: Step Icon, name: icon, widget: string, hint: Icons have to be placed in the backend manually }
                  - { label: X-Positioning, name: x_positioning, widget: number, valueType: int, hint: 'This allows to position the object manually along the a x-axis. Values will be translated to percentages.' }
      - name: 'about'
        label: 'About #ooo'
        file: 'about.md'
        fields:
          - { label: Layout, name: layout, widget: hidden, default: about }
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: markdown }
          - { label: About Members, name: about_members, widget: markdown }
          - { label: About Advisors, name: about_advisors, widget: markdown }
      - name: 'donate'
        label: 'Donate'
        file: 'donate.md'
        fields:
          - { name: layout, widget: hidden, default: chess_view }
          - { name: title, label: Title, widget: string }
          - { name: intro, label: Intro, widget: markdown }
          - name: 'items'
            label: 'Oranizations'
            widget: 'list'
            fields:
              - { name: title, label: Organization title, widget: string, required: true }
              - { name: content, Label: Organization Description, widget: markdown }
              - { name: image, label: Logo, widget: image }
              - { name: background_image, label: Background, widget: image }
              - name: 'action'
                label: 'Actions'
                widget: 'list'
                hint: 'please only make use of the "active" function on the last button, as the UI otherwise will get cluttered.'
                fields:
                  - { name: title, label: Button Text, widget: string }
                  - { name: link, label: URL, widget: string, hint: Please enter a valid URL }
                  - { name: active, label: Active, widget: boolean, default: true }
                  - { name: message, label: Info Message, widget: markdown, hint: This message will only be displayed if the button is deactivated }
      - name: 'getinvolved'
        label: Get Involved!
        file: 'get_involved.md'
        fields:
          - { name: layout, widget: hidden, default: chess_view }
          - { name: title, label: Title, widget: string, required: true }
          - { name: intro, layout: Intro Text, widget: markdown }
          - name: items
            label: How to get involved?
            widget: list
            fields:
              - { name: title, label: Title, widget: string }
              - { name: content, label: Description, widget: markdown }
              - { name: image, label: Background Image, widget: image, hint: Image/Logo which will be displayed next to the item }
              - { name: background_image, label: Background, widget: image }
      - name: 'imprint'
        label: 'Imprint'
        file: 'imprint.md'
        fields:
          - { name: static, widget: hidden, default: static }
          - { name: title, label: Title, widget: string, required: true }
          - { name: last_updated, layout: Last Updated, widget: string }
          - {label: "Body", name: "body", widget: "markdown", hint: "Include {% include contact.html %} to display the contact information."}
          - name: 'contact'
            label: 'Contact'
            widget: 'object'
            fields:
              - { name: name, label: Name, widget: string }
              - { name: street, label: Street | Address 1, widget: string }
              - { name: location, label: Location | Address 2, widget: string }
              - { name: phone, label: Phone, widget: string }
              - { name: email, label: Email, widget: string }
      - name: 'privacy policy'
        label: 'Privacy Policy'
        file: 'privacy_policy.md'
        fields:
          - { name: static, widget: hidden, default: static }
          - { name: title, label: Title, widget: string, required: true }
          - { name: last_updated, layout: Last Updated, widget: string }
          - {label: "Body", name: "body", widget: "markdown"}
  - name: 'data'
    label: 'Data'
    delete: false
    editor:
      preview: false
    files:
      - name: 'defaults'
        label: 'Global Defaults'
        file: '_data/defaults.yml'
        extension: 'yml'
        fields:
          - name: 'contact'
            label: 'Contact'
            widget: 'object'
            fields:
              - { name: email, label: eMail, widget: string }
              - { name: twitter, label: Twitter Username, widget: string }
          - name: 'channels'
            label: 'Social Channels'
            widget: 'list'
            allow_add: false
            fields:
              - { name: channel, label: Channel Title, widget: string }
              - { name: fa-icon, label: Fontawesome-Icon, widget: string }
              - { name: link, label: Link to Account, string: widget }
      - name: 'faq'
        label: 'FAQ'
        file: '_data/faq.yml'
        extension: 'yml'
        fields:
          - name: 'faqs'
            label: 'FAQ Sections'
            widget: 'list'
            fields:
              - { name: section, label: Section, widget: string }
              - name: 'faq'
                label: 'FAQ'
                widget: 'list'
                fields:
                  - { name: q, label: Question, widget: string }
                  - { name: a, label: Answer, widget: markdown }
      - name: 'product'
        label: 'Dummy Product'
        file: '_data/product.yml'
        extension: 'yml'
        fields:
          - { name: product, label: Product Title, widget: string }
          - { name: price, label: Price, widget: string }
          - { name: currency, label: Currency, widget: string, default: USD }
          - name: 'images'
            label: 'Images'
            widget: 'list'
            field: { name: image, label: Image, widget: image }
          - { name: active, label: Active, widget: boolean, hint: This allows you to show the buy button either as active or greyed out }
          - { name: button_text, label: Button Text, widget: string }
          - { name: description, label: Description, widget: markdown }
      - name: 'team'
        label: 'Team'
        file: '_data/team.yml'
        extension: 'yml'
        fields:
          - label: 'Team Members'
            name: 'team'
            widget: 'list'
            fields:
              - { label: Name, name: name, widget: string, default: true }
              - { label: Position, name: position, widget: string }
              - { label: About, name: about, widget: markdown }
              - { label: Profile Picture, name: img, widget: image }
              - { label: Role, name: role, widget: select, options: ["advisor", "member"]}
              - label: 'Contact'
                name: 'contact'
                widget: 'object'
                fields:
                  - { label: Linkedin, name: linkedin, widget: string }
                  - { label: Twitter, name: twitter, widget: string }
                  - { label: eMail, name: email, widget: string }
      - name: 'nav'
        label: 'Navigation'
        file: '_data/nav.yml'
        extension: 'yml'
        fields:
          - name: 'main'
            layout: 'Main Navigation'
            widget: 'list'
            fields:
              - { name: name, layout: Link Name, widget: string, required: true }
              - { name: url, layout: URL, widget: string, required: true }
              - { name: active, layout: Active, widget: boolean }
          - name: 'footer'
            layout: 'Navigation Additions for Footer'
            widget: 'list'
            hint: 'Elements added to the footer navigation list will be solely display (alongside the main navigation elements) in the footer section of the website.'
            fields:
              - { name: name, layout: Link Name, widget: string, required: true }
              - { name: url, layout: URL, widget: string, required: true }
              - { name: active, layout: Active, widget: boolean }
          - name: 'mobile'
            layout: 'Mobile Navigation'
            widget: 'list'
            fields:
              - { name: name, layout: Link Name, widget: string, required: true }
              - { name: url, layout: URL, widget: string, required: true }
              - { name: icon, layout: Icon, widget: string, hint: This is connected to included svg icons. Please do not change. }
              - { name: active, layout: Active, widget: boolean }
